# Generated by Django 4.2.2 on 2023-06-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='frade',
            new_name='grade',
        ),
    ]
