# Generated by Django 4.2.2 on 2023-06-27 22:11

import aluno.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_student_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='situation',
            field=models.CharField(choices=[('Cursando', 'Cursando'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default=aluno.enums.Situation['APROVADO'], max_length=100),
        ),
    ]
